services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3307:3306"
  ###< doctrine/doctrine-bundle ###

  messenger:
    ports:
      - "5672:5672"
      - "15672:15672"

  ###> symfony/mailer ###
  mailpit:
    ports:
      - "1025:1025"
      - "8025:8025"
  ###< symfony/mailer ###

  # Canaux marketplace exposés en local
  voltura:
    ports:
      - "3001:3000"
  cartelio:
    ports:
      - "3002:3000"
  zelmark:
    ports:
      - "3003:3000"
