services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-omnisync}
      # You should definitely change the password in production
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-omnisync}
      MYSQL_USER: ${MYSQL_USER:-omnisync}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER:-omnisync}", "-p${MYSQL_PASSWORD:-omnisync}"]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - database_data:/var/lib/mysql:rw
  ###< doctrine/doctrine-bundle ###

  messenger:
    image: rabbitmq:3.13-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-omnisync}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-omnisync}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - messenger_data:/var/lib/rabbitmq:rw

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
  messenger_data:
