services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3307:3306"
  ###< doctrine/doctrine-bundle ###

  messenger:
    ports:
      - "5672"
      - "15672"

  ###> symfony/mailer ###
  mailpit:
    ports:
      - "1025:1025"
      - "8025:8025"
  ###< symfony/mailer ###
